namespace: Cerner.DigitalFactory.Error_Notification
properties:
  - config: "{\"errorConfName\":\"phase1\",\"errorHandlers\":[{\"handler\":{\"id\":\"1\",\"name\":\"logger\",\"config\":{\"_comment\":\"Your comment string goes here...\",\"values\":[{\"value\":{\"name\":\"error_provider\",\"data\":\"SMAX\"}},{\"value\":{\"name\":\"error_log_file\",\"data\":\"mpp_oo_error.logs\"}},{\"value\":{\"name\":\"error_log_file_folder\",\"data\":\"mpp_eod_oo\"}},{\"value\":{\"name\":\"base_log_folder\",\"data\":\"/var/log/oo\"}}]}}},{\"handler\":{\"id\":\"2\",\"name\":\"email\",\"config\":{\"values\":[{\"value\":{\"name\":\"operator_email\",\"data\":\"Rakesh.Sharma@cerner.com,Ashwini.Shalke@cerner.com,SirshaKrishna.Yalam@cerner.com,Derick.Palos@Cerner.com\"}},{\"value\":{\"name\":\"email_subject\",\"data\":\"\"}},{\"value\":{\"name\":\"email_body\",\"data\":\"\"}},{\"value\":{\"name\":\"requestor_email_body\",\"data\":\"\"}},{\"value\":{\"name\":\"signature\",\"data\":\"\"}},{\"value\":{\"name\":\"informUser\",\"data\":\"yes\"}}]}}},{\"handler\":{\"id\":\"3\",\"name\":\"smax_error\",\"config\":{\"values\":[{}]}}}],\"errorActionMapping\":{\"default\":{\"actions\":[{\"action\":{\"id\":\"1\",\"config\":{\"values\":[{\"value\":{\"name\":\"path\",\"data\":\"\\\\tmp\\\\aa1.txt\"}}]}}},{\"action\":{\"id\":\"2\"}},{\"action\":{\"id\":\"3\"}}]},\"failSafe\":{\"actions\":[{\"action\":{\"id\":\"2\",\"config\":{\"values\":[{\"value\":{\"name\":\"email_subject\",\"data\":\"Fail Safe Error Logging Action\"}}]}}}]},\"errorTypes\":[{\"error\":{\"regex\":\"eX*\",\"actions\":[{\"action\":{\"id\":\"1\",\"config\":{\"values\":[{\"value\":{\"name\":\"path\",\"data\":\"\\\\tmp\\\\aa3.txt\"}}]}}}]}},{\"error\":{\"regex\":\"eX999\",\"actions\":[{\"action\":{\"id\":\"1\",\"config\":{\"values\":[{\"value\":{\"name\":\"path\",\"data\":\"\\\\tmp\\\\aa4.txt\"}}]}}}]}},{\"error\":{\"regex\":\"eX*\",\"actions\":[{\"action\":{\"id\":\"1\",\"config\":{\"values\":[{\"value\":{\"name\":\"path\",\"data\":\"\\\\tmp\\\\aa5.txt\"}}]}}}]}}]}}"
  - loggerName: logger
  - emailerName: email
  - incidentCreatorName: incident
  - monitoringTriggerName: monitoring
  - parameterMapping: 'error_provider,error_log_file,error_log_file_folder,base_log_folder;operator_email,email_subject,email_body,requestor_email_body,signature,informUser;path;path;path;'
  - smaxErrorHandlerName: smax_error
  - eod_config: "{\"errorConfName\":\"phase1\",\"errorHandlers\":[{\"handler\":{\"id\":\"1\",\"name\":\"logger\",\"config\":{\"_comment\":\"Your comment string goes here...\",\"values\":[{\"value\":{\"name\":\"error_provider\",\"data\":\"SMAX\"}},{\"value\":{\"name\":\"error_log_file\",\"data\":\"mpp_oo_error.logs\"}},{\"value\":{\"name\":\"error_log_file_folder\",\"data\":\"mpp_eod_oo\"}},{\"value\":{\"name\":\"base_log_folder\",\"data\":\"/var/log/oo\"}}]}}},{\"handler\":{\"id\":\"2\",\"name\":\"email\",\"config\":{\"values\":[{\"value\":{\"name\":\"operator_email\",\"data\":\"rakesh.sharma@cerner.com,rajesh.singh5@microfocus.com\"}},{\"value\":{\"name\":\"email_subject\",\"data\":\"\"}},{\"value\":{\"name\":\"email_body\",\"data\":\"\"}},{\"value\":{\"name\":\"requestor_email_body\",\"data\":\"\"}},{\"value\":{\"name\":\"signature\",\"data\":\"\"}},{\"value\":{\"name\":\"informUser\",\"data\":\"yes\"}}]}}},{\"handler\":{\"id\":\"3\",\"name\":\"smax_error\",\"config\":{\"values\":[{}]}}}],\"errorActionMapping\":{\"default\":{\"actions\":[{\"action\":{\"id\":\"1\",\"config\":{\"values\":[{\"value\":{\"name\":\"path\",\"data\":\"\\\\tmp\\\\aa1.txt\"}}]}}},{\"action\":{\"id\":\"2\"}},{\"action\":{\"id\":\"3\"}}]},\"failSafe\":{\"actions\":[{\"action\":{\"id\":\"2\",\"config\":{\"values\":[{\"value\":{\"name\":\"email_subject\",\"data\":\"Fail Safe Error Logging Action\"}}]}}}]},\"errorTypes\":[{\"error\":{\"regex\":\"eX*\",\"actions\":[{\"action\":{\"id\":\"1\",\"config\":{\"values\":[{\"value\":{\"name\":\"path\",\"data\":\"\\\\tmp\\\\aa3.txt\"}}]}}}]}},{\"error\":{\"regex\":\"eX999\",\"actions\":[{\"action\":{\"id\":\"1\",\"config\":{\"values\":[{\"value\":{\"name\":\"path\",\"data\":\"\\\\tmp\\\\aa4.txt\"}}]}}}]}},{\"error\":{\"regex\":\"eX*\",\"actions\":[{\"action\":{\"id\":\"1\",\"config\":{\"values\":[{\"value\":{\"name\":\"path\",\"data\":\"\\\\tmp\\\\aa5.txt\"}}]}}}]}}]}}"
